os: Visual Studio 2017

environment:
  image: Visual Studio 2017
  SignClientSecret:
    secure: <add value here>
  SignClientUser:
    secure: <add value here>

install:
  - ps: nuget install -ExcludeVersion SignClient -Version 0.9.0 -OutputDirectory .\build\

build_script:
  - cmd: msbuild /t:restore;build /p:Configuration=Release /m .\Open-Xml-SDK.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: msbuild /t:pack /p:Configuration=Release .\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: .\build\SignPackage.ps1

test_script:
  - dotnet vstest /logger:trx bin\Release\DocumentFormat.OpenXml.Tests\netcoreapp1.0\DocumentFormat.OpenXml.Tests.dll /Framework:FrameworkCore10
  - vstest.console.exe /logger:appveyor bin\Release\DocumentFormat.OpenXml.Tests\net46\DocumentFormat.OpenXml.Tests.dll /Framework:Framework45
  - vstest.console.exe /logger:appveyor bin\Release\DocumentFormat.OpenXml.Tests\net452\DocumentFormat.OpenXml.Tests.dll /Framework:Framework45

deploy:
  provider: NuGet
  server: https://dotnet.myget.org/F/open-xml-sdk/api/v2/package
  api_key:
    secure: +uagaLcg+y8G8ZBxlXm0E5VmTHeT030NeoyHZGU8V7MtIPc1+VUXru0mAPVh0KhK
  on:
    branch: [master, vNext, Office2016]
