os: Visual Studio 2017

environment:
  image: Visual Studio 2017
  SignClientSecret:
    secure: K2IZr2uNWnPFxfLYnpwbUIAQmLHYY5IjWvdRXfdUUMU=
  SignClientUser:
    secure: vcaNFKm7ZLGnBM/RkByidsmmpx0I16RcsdOsj3ewh8Ga3ThHll8BiG9xmW0IymLD
  Configuration: Release
  EnableCodeCoverage: true

install:
  - ps: nuget install -ExcludeVersion SignClient -Version 0.9.0 -OutputDirectory .\build\

build_script:
  - cmd: msbuild /t:restore;build /m .\Open-Xml-SDK.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: msbuild /t:pack /m .\DocumentFormat.OpenXml\DocumentFormat.OpenXml.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ps: .\build\SignPackage.ps1

test_script:
  - cmd: msbuild /t:test .\Open-Xml-SDK.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

deploy:
  provider: NuGet
  server: https://dotnet.myget.org/F/open-xml-sdk/api/v2/package
  api_key:
    secure: +uagaLcg+y8G8ZBxlXm0E5VmTHeT030NeoyHZGU8V7MtIPc1+VUXru0mAPVh0KhK
  on:
    branch: [master, vNext, Office2016]
